{
  "openapi": "3.0.0",
  "info": {
    "description": "Server hosting Pru 2.0 API",
    "version": "1.0.0",
    "title": "Pru 2.0 API",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@prudential.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "https://api.prudential.com/v1"
    },
    {
      "url": "http://api.prudential.com/v1"
    }
  ],
  "tags": [
    {
      "name": "Customer",
      "description": "Customer API"
    },
    {
      "name": "Product",
      "description": "Product API"
    },
    {
      "name": "Policy",
      "description": "Policy API"
    },
    {
      "name": "Claim",
      "description": "Claim API"
    },
    {
      "name": "Underwriting",
      "description": "Underwriting API"
    },
    {
      "name": "Document",
      "description": "Document API"
    },
    {
      "name": "Billing",
      "description": "Billing API"
    },
    {
      "name": "Payment",
      "description": "Payment API"
    },
    {
      "name": "Agent",
      "description": "Agent API"
    },
    {
      "name": "Quote",
      "description": "Quote API"
    },
    {
      "name": "Proposal",
      "description": "Proposal API"
    },
    {
      "name": "Workflow",
      "description": "Workflow API"
    },
    {
      "name": "Fund",
      "description": "Fund API"
    },
    {
      "name": "Campaign",
      "description": "Campaign API"
    },
    {
      "name": "Doctor",
      "description": "Doctor API"
    },
    {
      "name": "User",
      "description": "User API"
    },
    {
      "name": "Data",
      "description": "Data API"
    },
    {
      "name": "Message",
      "description": "Messaging API"
    },
    {
      "name": "Hospital",
      "description": "Hospital API"
    },
    {
      "name": "Geo location",
      "description": "Geo location API"
    },
    {
      "name": "Resource",
      "description": "Resource API"
    },
    {
      "name": "Partner",
      "description": "Partner API"
    },
    {
      "name": "Chat",
      "description": "Chat API"
    },
    {
      "name": "Notification",
      "description": "Notification API"
    },
    {
      "name": "Group",
      "description": "Group API"
    },
    {
      "name": "Event",
      "description": "Event API"
    },
    {
      "name": "Conversation",
      "description": "Conversation API"
    },
    {
      "name": "Wearables",
      "description": "Wearables API"
    }
  ],
  "paths": {
    "/customer": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Create new customer",
        "description": "",
        "operationId": "createCustomer"
      }
    },
    "/customer/search": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Find customers by query criteria",
        "description": "",
        "operationId": "findCustomersByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "search:customers"
            ]
          }
        ]
      }
    },
    "/customer/exist": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Check if customer exist",
        "description": "",
        "operationId": "existCustomer",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get customer by Id",
        "description": "Returns a single customer",
        "operationId": "getCustomerById",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customer"
        ],
        "summary": "Update an existing customer",
        "description": "",
        "operationId": "updateCustomer",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete a customer",
        "description": "",
        "operationId": "deleteCustomer",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/address": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all customer addresses",
        "description": "",
        "operationId": "getCustomerAddresses",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/address/{key}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get selected customer address",
        "description": "",
        "operationId": "getCustomerAddress",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer address",
        "description": "",
        "operationId": "updateCustomerAddress",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete selected address",
        "description": "",
        "operationId": "deleteCustomerAddress",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/contact": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all customer contacts",
        "description": "",
        "operationId": "getCustomerContacts",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/contact/{key}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get selected customer contact",
        "description": "",
        "operationId": "getCustomerContact",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer contact",
        "description": "",
        "operationId": "updateCustomerContact",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete selected contact",
        "description": "",
        "operationId": "deleteCustomerContact",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/preference": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all customer preferences",
        "description": "",
        "operationId": "getCustomerPreferences",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/preference/{key}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get selected customer preference",
        "description": "",
        "operationId": "getCustomerPreference",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer preference",
        "description": "",
        "operationId": "updateCustomerPreference",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete customer preference",
        "description": "",
        "operationId": "deleteCustomerPreference",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/bankaccount": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all customer bank accounts",
        "description": "",
        "operationId": "getCustomerBankAccounts",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/bankaccount/{key}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get selected customer bank account",
        "description": "",
        "operationId": "getCustomerBankAccount",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer bank account",
        "description": "",
        "operationId": "updateCustomerBankAccount",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete selected bank account",
        "description": "",
        "operationId": "deleteCustomerBankAccount",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/agent": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get agent of customer",
        "description": "",
        "operationId": "getCustomerAgent",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/policy": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all policies of customer",
        "description": "",
        "operationId": "getCustomerPolicies",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/claim": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all claims of customer",
        "description": "",
        "operationId": "getCustomerClaims",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/lifestyle": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get customer lifestyle details",
        "description": "",
        "operationId": "getCustomerLifestyle",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer lifestyle details",
        "description": "",
        "operationId": "updateCustomerLifestyle",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/lifestyle/estimateBMI": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Post Profile Picture for BMI",
        "description": "",
        "operationId": "estimateBMI",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/lifestyle/BMIfeedback": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Post customer BMI feedback",
        "description": "",
        "operationId": "BMIfeedback",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/transaction": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get transaction history of customer",
        "description": "",
        "operationId": "getCustomerTransactions",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/payment": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get payment history of customer",
        "description": "",
        "operationId": "getCustomerPayments",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/billing": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get billing detail of customer",
        "description": "",
        "operationId": "getCustomerBillingDetail",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/billing/invoice": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get customer invoice",
        "description": "",
        "operationId": "getCustomerInvoices",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/billing/stmt": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get customer account statement",
        "description": "",
        "operationId": "getCustomerAccountStmt",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/workflow": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all workflows of customer",
        "description": "",
        "operationId": "getCustomerWorkflows",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/notify": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Send customer notification",
        "description": "",
        "operationId": "notifyCustomer",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/event": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get events of customer",
        "description": "Return all events associated with customer. This includes past and future events",
        "operationId": "getCustomerEvents",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Create event for this customer",
        "description": "Create event for this customer",
        "operationId": "createEvent",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/conversation": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Create conversation session with this customer",
        "description": "Create conversation session for this customer",
        "operationId": "createCustomerConversation",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customer"
        ],
        "summary": "Update conversation status",
        "description": "Update conversation status",
        "operationId": "updateConversationStatus",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all conversations with this customer",
        "description": "Get all conversations with this customer",
        "operationId": "getCustomerConversations",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/conversation/{convId}/message": {
      "post": {
        "tags": [
          "Conversation"
        ],
        "summary": "Create message for this conversation",
        "description": "Create message for this conversation",
        "operationId": "createConversationMessage",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Conversation"
        ],
        "summary": "Get messages for this conversation",
        "description": "Get messages for this conversation",
        "operationId": "getConversationMessages",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/conversation/{convId}/outcome": {
      "post": {
        "tags": [
          "Conversation"
        ],
        "summary": "Create outcome of this conversation",
        "description": "Create outcome of this conversation",
        "operationId": "createConversationOutcome",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Conversation"
        ],
        "summary": "Get outcome of this conversation",
        "description": "Get outcome of this conversation",
        "operationId": "getConversationOutcome",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Conversation"
        ],
        "summary": "Update outcome of this conversation",
        "description": "Update outcome of this conversation",
        "operationId": "updateConversationOutcome",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/complaint": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get customer complaints",
        "description": "",
        "operationId": "getCustomerComplaints",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Create customer complaint",
        "description": "",
        "operationId": "createCustomerComplaint",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/document": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get customer documents",
        "description": "",
        "operationId": "getCustomerDocuments",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Add customer documents",
        "description": "",
        "operationId": "addCustomerDocuments",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/comms": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get customer communications",
        "description": "",
        "operationId": "getCustomerComms",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/medicine/order/{orderId}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "get medicine order for this customer",
        "description": "get medicine order for this customer",
        "operationId": "getMedicineOrder",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "get medicine order for this customer",
        "description": "get medicine order for this customer",
        "operationId": "fulfillOrder",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/medicine": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Order medicine for this customer",
        "description": "Order medicine for this customer",
        "operationId": "orderMedicine",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/ambulance": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Call ambulance for this customer",
        "description": "Call ambulance for this customer",
        "operationId": "callAmbulance",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/consultation": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all consultations",
        "description": "Get all consultations",
        "operationId": "getAllConsultations",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/consultation/{consultationId}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get consultation by Id",
        "description": "Get  consultation by Id",
        "operationId": "getConsultationById",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/prescription": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all prescriptions",
        "description": "Get all prescriptions",
        "operationId": "getAllPrescriptions",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/prescription/{prescriptionId}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get prescription by Id",
        "description": "Get prescription by Id",
        "operationId": "getPrescriptionById",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/test": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all lab tests",
        "description": "Get all lab tests",
        "operationId": "getAllLabTests",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/test/{key}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get lab tests by Id",
        "description": "Get lab tests by Id",
        "operationId": "getLabTestsById",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/health/casenote": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all case notes",
        "description": "Get all case notes",
        "operationId": "getAllCaseNotes",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/relations": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all customer relations",
        "description": "Get all customer relations",
        "operationId": "getAllRelations",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/relations/{key}": {
      "put": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer Relation",
        "description": "Update customer relation",
        "operationId": "updateCustomerRelation",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete selected relation",
        "description": "",
        "operationId": "deleteCustomerRelation",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers",
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/externalIds": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all customer external Ids",
        "description": "",
        "operationId": "getCustomerExternalIds",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/externalIds/{key}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get selected externalId",
        "description": "",
        "operationId": "getCustomerExternalId",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer External Id",
        "description": "",
        "operationId": "updateCustomerExternalId",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete selected External Id",
        "description": "",
        "operationId": "deleteCustomerExternalId",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/connect": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Create connect with customer",
        "description": "Create connect with customer",
        "operationId": "createCustomerConnect",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all Connect with this customer",
        "description": "Get all Connect with this customer",
        "operationId": "getAllCustomerConnect",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/connect/{key}": {
      "put": {
        "tags": [
          "Customer"
        ],
        "summary": "Update Customer Connect ",
        "description": "Update Customer Connect ",
        "operationId": "updateCustomerConnect",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete selected customer connect",
        "description": "",
        "operationId": "deleteCustomerConnect",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/group": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all groups for this customer",
        "description": "Get all groups for this customer",
        "operationId": "getAllCustomerGroup",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/group/join": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Join the group",
        "description": "Join the group",
        "operationId": "joinGroup",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/group/leave": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Leave the group",
        "description": "Leave the group",
        "operationId": "leaveGroup",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/group/addMember": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Add member to the group",
        "description": "Add member to the group",
        "operationId": "addGroupMember",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/wallet": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get wallet detail of customer",
        "description": "",
        "operationId": "getCustomerWalletDetail",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer wallet",
        "description": "",
        "operationId": "updateCustomerWallet",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/termsCondition": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all customer termsCondition",
        "description": "",
        "operationId": "getAllCustomerTermsCondition",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/termsCondition/{key}": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get selected customer termsCondition",
        "description": "",
        "operationId": "getCustomerTermsCondition",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customer"
        ],
        "summary": "Update customer termsCondition",
        "description": "",
        "operationId": "updateCustomerTermsCondition",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete selected termsCondition",
        "description": "",
        "operationId": "deleteCustomerTermsCondition",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/termsCondition/{key}/latest": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get selected customer termsCondition",
        "description": "",
        "operationId": "getLatestCustomerTermsCondition",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/calendar": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Get Customer Calendar",
        "description": "Get Customer Calendar",
        "operationId": "getCustomerCalendar",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/reward/loyaltypoints/credit": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Credit reward loyaltypoints to Customer",
        "description": "Credit reward loyaltypoints to Customer",
        "operationId": "creditPoints",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/reward/loyaltypoints": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get Customer loyaltypoints",
        "description": "Get Customer loyaltypoints",
        "operationId": "getCustomerLoyaltyPoints",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/reward/voucher/issue": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Issue voucher to customer",
        "description": "Issue voucher to customer",
        "operationId": "issueVoucher",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/reward/voucher/detail": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Voucher detail issued to customer",
        "description": "Voucher detail issued to customer",
        "operationId": "voucherDetail",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/reward/vouchers": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get Customer vouchers",
        "description": "Get Customer vouchers",
        "operationId": "getCustomerVouchers",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/reward/{name}/status": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get Customer Reward status",
        "description": "Get Customer Reward status",
        "operationId": "getCustomerRewardStatus",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/reward/earn": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Earn customer reward",
        "description": "Earn customer reward",
        "operationId": "earnCustomerReward",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/wearables": {
      "get": {
        "tags": [
          "Customer"
        ],
        "summary": "Get all connected wearables",
        "description": "Get all connected wearables",
        "operationId": "getAllCustomerWearables",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{id}/wearable/{name}": {
      "post": {
        "tags": [
          "Customer"
        ],
        "summary": "Initiate wearable connection",
        "description": "Initiate wearable connection",
        "operationId": "initiateWearableConnection",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customer"
        ],
        "summary": "update wearable connection status",
        "description": "update wearable connection status",
        "operationId": "updateWearableConnection",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer"
        ],
        "summary": "Delete wearable connection",
        "description": "Delete wearable connection",
        "operationId": "deleteWearableConnection",
        "security": [
          {
            "pru_api_auth": [
              "delete:customers"
            ]
          }
        ]
      }
    },
    "/product": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Create new product",
        "description": "",
        "operationId": "createProduct",
        "security": [
          {
            "pru_api_auth": [
              "write:products"
            ]
          }
        ]
      }
    },
    "/product/search": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Find products by query criteria",
        "description": "",
        "operationId": "findProductsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Find product by Id",
        "description": "Returns a single product",
        "operationId": "getProductById",
        "security": [
          {
            "pru_api_auth": [
              "read:products"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Product"
        ],
        "summary": "Update an existing product",
        "description": "",
        "operationId": "updateProduct",
        "security": [
          {
            "pru_api_auth": [
              "write:products"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Product"
        ],
        "summary": "Delete product",
        "description": "",
        "operationId": "deleteProduct",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/component": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "add product component to this product",
        "description": "",
        "operationId": "addProductComponent",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get all product components",
        "description": "Get all product components",
        "operationId": "getProductComponent",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/component/{compId}": {
      "delete": {
        "tags": [
          "Product"
        ],
        "summary": "Remove product component from product",
        "description": "",
        "operationId": "deleteProductComponent",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/component": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Create new Product Component",
        "description": "",
        "operationId": "createProductComponent",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/component/search": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Find product components by query criteria",
        "description": "",
        "operationId": "findProductComponentsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/component/{id}": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Find product component by Id",
        "description": "Returns a single product component",
        "operationId": "getProductComponentById",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Product"
        ],
        "summary": "Update an existing product component",
        "description": "",
        "operationId": "updateProductComponent",
        "security": [
          {
            "pru_api_auth": [
              "write:products"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Product"
        ],
        "summary": "Delete product component",
        "description": "",
        "operationId": "deleteProductComponent",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/compute": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "compute rules of this product",
        "description": "",
        "operationId": "compute",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/compute/{key}": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Stateful compute rules of this product",
        "description": "",
        "operationId": "computeByKey",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/generate/{templateId}": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Generate documents from product document template",
        "description": "",
        "operationId": "compute",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/transactioncontext": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get product TransactionContext",
        "description": "Get product TransactionContext",
        "operationId": "getProductTransactionContext",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/risk": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get Risk for a product",
        "description": "Get Risk for a product",
        "operationId": "getProductRisk",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/underwriting": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get Underwriting for product",
        "description": "Get Underwriting for product",
        "operationId": "getProductUnderwriting",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/saleschannel": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get Sales channel for a product",
        "description": "Get Sales channel for a product",
        "operationId": "getProductSalesChannel",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/coverage": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get Product coverage",
        "description": "Get Product coverage",
        "operationId": "getProductCoverage",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/catalog/{channel}": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get Product catalog channel",
        "description": "Get Product catalog channel",
        "operationId": "getProductCatalogChannel",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/catalog/{lbu}/{channel}": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get Product catalog channel",
        "description": "Get Product catalog channel",
        "operationId": "getProductCatalogByLBU",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/component/{componentType}": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get Product ComponentType by type",
        "description": "Get Product ComponentType by type",
        "operationId": "getProductComponentByType",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/product/{id}/lookup/{key}": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get Product lookup by key",
        "description": "Get Product lookup by key",
        "operationId": "getProductLookupByKey",
        "security": [
          {
            "pru_api_auth": [
              "write:products",
              "read:products"
            ]
          }
        ]
      }
    },
    "/quote": {
      "post": {
        "tags": [
          "Quote"
        ],
        "summary": "Create quote",
        "description": "",
        "operationId": "createQuote",
        "security": [
          {
            "pru_api_auth": [
              "write:customers",
              "read:customers"
            ]
          }
        ]
      }
    },
    "/proposal": {
      "post": {
        "tags": [
          "Proposal"
        ],
        "summary": "Submit proposal",
        "description": "",
        "operationId": "submitProposal",
        "security": [
          {
            "pru_api_auth": [
              "write:proposal",
              "read:proposal"
            ]
          }
        ]
      }
    },
    "/proposal/search": {
      "post": {
        "tags": [
          "Proposal"
        ],
        "summary": "Find proposal by query criteria",
        "description": "",
        "operationId": "findProposalsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "write:proposals",
              "read:proposals"
            ]
          }
        ]
      }
    },
    "/proposal/{id}": {
      "get": {
        "tags": [
          "Proposal"
        ],
        "summary": "Find proposal by Id",
        "description": "Return proposal by Id",
        "operationId": "getProposalById",
        "security": [
          {
            "pru_api_auth": [
              "write:proposals",
              "read:proposals"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Proposal"
        ],
        "summary": "Update proposal",
        "description": "",
        "operationId": "updateProposal",
        "security": [
          {
            "pru_api_auth": [
              "write:proposal",
              "read:proposal"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Proposal"
        ],
        "summary": "Delete proposal",
        "description": "",
        "operationId": "deleteProposal",
        "security": [
          {
            "pru_api_auth": [
              "write:proposal",
              "read:proposal"
            ]
          }
        ]
      }
    },
    "/agent": {
      "post": {
        "tags": [
          "Agent"
        ],
        "summary": "Create Agent",
        "description": "",
        "operationId": "createAgent",
        "security": [
          {
            "pru_api_auth": [
              "write:agents",
              "read:agents"
            ]
          }
        ]
      }
    },
    "/agent/search": {
      "post": {
        "tags": [
          "Agent"
        ],
        "summary": "Find agents by query criteria",
        "description": "",
        "operationId": "findAgentsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "write:agents",
              "read:agents"
            ]
          }
        ]
      }
    },
    "/agent/{id}": {
      "get": {
        "tags": [
          "Agent"
        ],
        "summary": "Find agent by Id",
        "description": "Return agent by Id",
        "operationId": "getAgentById",
        "security": [
          {
            "api_key": []
          }
        ]
      },
      "put": {
        "tags": [
          "Agent"
        ],
        "summary": "Update agent",
        "description": "",
        "operationId": "updateAgnt",
        "security": [
          {
            "pru_api_auth": [
              "write:agents"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Agent"
        ],
        "summary": "Delete agent",
        "description": "",
        "operationId": "deleteAgent",
        "security": [
          {
            "pru_api_auth": [
              "write:agents",
              "read:agents"
            ]
          }
        ]
      }
    },
    "/payment/initiate": {
      "get": {
        "tags": [
          "Payment"
        ],
        "summary": "Initiate payment through payment gateway",
        "description": "",
        "operationId": "initiatePayment",
        "security": [
          {
            "pru_api_auth": [
              "read:payments"
            ]
          }
        ]
      }
    },
    "/payment/checkout": {
      "post": {
        "tags": [
          "Payment"
        ],
        "summary": "Perform payment transaction",
        "description": "",
        "operationId": "paymentCheckout"
      }
    },
    "/payment": {
      "post": {
        "tags": [
          "Payment"
        ],
        "summary": "Update payment",
        "description": "",
        "operationId": "updatePayment"
      }
    },
    "/underwriting/check": {
      "post": {
        "tags": [
          "Underwriting"
        ],
        "summary": "Check underwriter",
        "description": "",
        "operationId": "underwriterCheck",
        "security": [
          {
            "pru_api_auth": [
              "read:underwritings"
            ]
          }
        ]
      }
    },
    "/underwriting/compute": {
      "post": {
        "tags": [
          "Underwriting"
        ],
        "summary": "Submit computation request to underwriter",
        "description": "",
        "operationId": "underwriterCompute",
        "security": [
          {
            "pru_api_auth": [
              "write:customers",
              "read:customers"
            ]
          }
        ]
      }
    },
    "/claim": {
      "post": {
        "tags": [
          "Claim"
        ],
        "summary": "Create claim",
        "description": "",
        "operationId": "createClaim",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/claim/search": {
      "post": {
        "tags": [
          "Claim"
        ],
        "summary": "Find claims by query criteria",
        "description": "",
        "operationId": "findClaimsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "search:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Find claim by Id",
        "description": "Returns a single Claim",
        "operationId": "getClaimById",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Claim"
        ],
        "summary": "Update an existing claim",
        "description": "",
        "operationId": "updateClaim",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/hospital/{hospitalId}": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Get claim Hospital",
        "description": "Returns a Claim Hospital",
        "operationId": "getClaimHospital",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/doctor/{doctorId}": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Get claim Doctor",
        "description": "Returns a Claim Doctor",
        "operationId": "getClaimDoctor",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/document": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Get claim Documents",
        "description": "Returns a Claim Documents",
        "operationId": "getClaimDocuments",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Claim"
        ],
        "summary": "Create claim Document",
        "description": "create a Claim Documents",
        "operationId": "createClaimDocument",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/document/{documentId}": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Get claim Document by documentId",
        "description": "Returns a Claim Document by documentId",
        "operationId": "getClaimDocumentById",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Claim"
        ],
        "summary": "Update claim Document by DocumentId",
        "description": "update a Claim Document by DocumentId",
        "operationId": "updateClaimDocumentById",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Claim"
        ],
        "summary": "Delete claim Document by DocumentId",
        "description": "delete a Claim Document by DocumentId",
        "operationId": "deleteClaimDocumentById",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/policy/{policyId}": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Get claim policy",
        "description": "Returns a Claim policy",
        "operationId": "getClaimPolicy",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/client/{clientId}": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Get claim client",
        "description": "Returns a Claim client",
        "operationId": "getClaimClient",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/payment": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Get claim payment",
        "description": "Returns a Claim payment",
        "operationId": "getClaimPayment",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      }
    },
    "/claim/death": {
      "post": {
        "tags": [
          "Claim"
        ],
        "summary": "Register death Claim",
        "description": "",
        "operationId": "createDeathClaim",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/claim/injury": {
      "post": {
        "tags": [
          "Claim"
        ],
        "summary": "Register injury Claim",
        "description": "",
        "operationId": "createInjuryClaim",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/claim/hospitalisation": {
      "post": {
        "tags": [
          "Claim"
        ],
        "summary": "Register hospitalisation Claim",
        "description": "",
        "operationId": "createHospitalisationClaim",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/status": {
      "get": {
        "tags": [
          "Claim"
        ],
        "summary": "Get Claim status",
        "description": "Get Claim status",
        "operationId": "getClaimStatusById",
        "security": [
          {
            "pru_api_auth": [
              "read:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/dispute": {
      "post": {
        "tags": [
          "Claim"
        ],
        "summary": "Raise Claim Dispute",
        "description": "",
        "operationId": "raiseClaimDispute",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/claim/{id}/feedback": {
      "post": {
        "tags": [
          "Claim"
        ],
        "summary": "Submit Claim Dispute",
        "description": "",
        "operationId": "submitClaimFeedback",
        "security": [
          {
            "pru_api_auth": [
              "write:claims"
            ]
          }
        ]
      }
    },
    "/policy": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Create Policy",
        "description": "",
        "operationId": "createPolicy",
        "security": [
          {
            "pru_api_auth": [
              "search:policies"
            ]
          }
        ]
      }
    },
    "/policy/search": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Find policies by query criteria",
        "description": "",
        "operationId": "findPoliciesByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "search:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Find policy by Id",
        "description": "Returns a single policy",
        "operationId": "getPolicyById",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Policy"
        ],
        "summary": "Update an existing policy",
        "description": "",
        "operationId": "updatePolicy",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Policy"
        ],
        "summary": "Terminate Policy",
        "description": "",
        "operationId": "terminatePolicy",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/product/{productId}": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy product",
        "description": "Return policy product",
        "operationId": "getPolicyProduct",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/productOption": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get all policy product option",
        "description": "Return all policy product option",
        "operationId": "getAllPolicyProductOption",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/proposal/{proposalId}": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy proposal",
        "description": "return policy proposal",
        "operationId": "getPolicyProposal",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/paymentOption": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy payment option",
        "description": "return policy payment option",
        "operationId": "getPolicyPaymentOption",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/lifeAssured": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get All policy Life assured customers",
        "description": "return All policy Life assured customers",
        "operationId": "getAllPolicyLifeAssured",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/lifeAssured/{customerId}": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy Life assured customer",
        "description": "return policy Life assured customer",
        "operationId": "getPolicyLifeAssured",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/beneficiary": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get All policy beneficiaries",
        "description": "return All policy beneficiaries",
        "operationId": "getAllPolicyBeneficiary",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "create policy beneficiary",
        "description": "create policy beneficiary",
        "operationId": "createPolicyBeneficiary",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/beneficiary/{beneficiaryId}": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy beneficiary by beneficiaryId",
        "description": "return policy beneficiary",
        "operationId": "getPolicyBeneficiaryById",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Policy"
        ],
        "summary": "update policy beneficiary",
        "description": "update policy beneficiary",
        "operationId": "updatePolicyBeneficiaryById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Policy"
        ],
        "summary": "delete policy beneficiary",
        "description": "delete policy beneficiary",
        "operationId": "deletePolicyBeneficiaryById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/payer": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get All policy payers",
        "description": "return All policy payers",
        "operationId": "getAllPolicyPayers",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/payer/{payerId}": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy payer",
        "description": "return policy payer",
        "operationId": "getPolicyPayer",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/owner/{ownerId}": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get  policy owner",
        "description": "return  policy owner",
        "operationId": "getPolicyOwner",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/client": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get All policy Clients",
        "description": "return All policy Clients",
        "operationId": "getAllPolicyClients",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/client/{clientId}": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy Client",
        "description": "return policy Client",
        "operationId": "getPolicyClients",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/transaction": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy Transactions",
        "description": "return policy Transactions",
        "operationId": "getPolicyTransactions"
      }
    },
    "/policy/{id}/billingDetail": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy Billing Detail",
        "description": "return policy Billing Detail",
        "operationId": "getPolicyBillingDetail",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "create policy Billing Detail",
        "description": "create policy Billing Detail",
        "operationId": "createPolicyBillingDetail",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Policy"
        ],
        "summary": "update policy Billing Detail",
        "description": "update policy Billing Detail",
        "operationId": "updatePolicyBillingDetail",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/statement": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy statement",
        "description": "",
        "operationId": "getPolicyStatementById",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/document": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy document",
        "description": "",
        "operationId": "getPolicyDocumentById",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/status": {
      "get": {
        "tags": [
          "Policy"
        ],
        "summary": "Get policy status",
        "description": "",
        "operationId": "getPolicyStatusById",
        "security": [
          {
            "pru_api_auth": [
              "read:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/payPremium": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Pay policy Premium",
        "description": "",
        "operationId": "payPolicyPremiumById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/revival": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Revive policy",
        "description": "",
        "operationId": "revivePolicyPremiumById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/surrender": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Surrender policy",
        "description": "",
        "operationId": "surrenderPolicyPremiumById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/billingDetail/updateAddress": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Update policy Communication Address",
        "description": "",
        "operationId": "updatePolicyBillingAddress",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/changePremium": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Change Policy premium",
        "description": "",
        "operationId": "changePolicyPremiumById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/changeSumAssured": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Change Policy sum assured",
        "description": "",
        "operationId": "changePolicySumAssuredById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/changePaymentType": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Change Policy Payment Type",
        "description": "",
        "operationId": "changePolicyPaymentTypeById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/changePaymentDetail": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Change Policy Payment detail",
        "description": "",
        "operationId": "changePolicyPaymentDetailById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/changePaymentFrequency": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Change Policy Payment Frequency",
        "description": "",
        "operationId": "changePolicyPaymentFrequencyById",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/policy/{id}/feedback": {
      "post": {
        "tags": [
          "Policy"
        ],
        "summary": "Submit Policy Feedback",
        "description": "",
        "operationId": "submitPolicyFeedback",
        "security": [
          {
            "pru_api_auth": [
              "write:policies"
            ]
          }
        ]
      }
    },
    "/document": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Create new Document",
        "description": "",
        "operationId": "createDocument",
        "security": [
          {
            "pru_api_auth": [
              "write:documents"
            ]
          }
        ]
      }
    },
    "/document/search": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Find documents by query criteria",
        "description": "",
        "operationId": "findDocumentsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "read:documents"
            ]
          }
        ]
      }
    },
    "/document/{id}": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Find document by Id",
        "description": "Return doumet by Id",
        "operationId": "getDocumentById",
        "security": [
          {
            "pru_api_auth": [
              "read:documents"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Document"
        ],
        "summary": "Update document",
        "description": "",
        "operationId": "updateDocument",
        "security": [
          {
            "pru_api_auth": [
              "write:documents"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Document"
        ],
        "summary": "Delete document",
        "description": "",
        "operationId": "deleteDocument",
        "security": [
          {
            "pru_api_auth": [
              "delete:documents"
            ]
          }
        ]
      }
    },
    "/document/{id}/metadata": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "get Metadata of Document",
        "description": "",
        "operationId": "getDocumentMetadata",
        "security": [
          {
            "pru_api_auth": [
              "read:documents"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "update Metadata of Document",
        "description": "",
        "operationId": "updateDocumentMetadata",
        "security": [
          {
            "pru_api_auth": [
              "write:documents"
            ]
          }
        ]
      }
    },
    "/document/{id}/version/{versionId}": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Update document version",
        "description": "",
        "operationId": "updateDocumentVersion",
        "security": [
          {
            "pru_api_auth": [
              "write:documents"
            ]
          }
        ]
      }
    },
    "/documents": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "get documents by Ids",
        "description": "Return doumet by Id",
        "operationId": "getDocumentsByIds",
        "security": [
          {
            "pru_api_auth": [
              "read:documents"
            ]
          }
        ]
      }
    },
    "/document/trends": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Trends",
        "description": "",
        "operationId": "getTrends",
        "security": [
          {
            "pru_api_auth": [
              "read:documents"
            ]
          }
        ]
      }
    },
    "/document/newsfeed": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get News feed",
        "description": "",
        "operationId": "getNewsFeed",
        "security": [
          {
            "pru_api_auth": [
              "read:documents"
            ]
          }
        ]
      }
    },
    "/document/newsfeed/{id}": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get detailed news by Id",
        "description": "Return detailed news by Id",
        "operationId": "getNewsFeedById",
        "security": [
          {
            "pru_api_auth": [
              "read:documents"
            ]
          }
        ]
      }
    },
    "/doctor/search": {
      "post": {
        "tags": [
          "Doctor"
        ],
        "summary": "Find doctor by query criteria",
        "description": "",
        "operationId": "findDoctorsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "search:doctors"
            ]
          }
        ]
      }
    },
    "/doctor/appointment": {
      "post": {
        "tags": [
          "Doctor"
        ],
        "summary": "Get Doctor Appointment",
        "description": "",
        "operationId": "getDoctorAppointment",
        "security": [
          {
            "pru_api_auth": [
              "write:doctors"
            ]
          }
        ]
      }
    },
    "/doctor/appointment/confirmation": {
      "post": {
        "tags": [
          "Doctor"
        ],
        "summary": "Confirm Doctor Appointment",
        "description": "",
        "operationId": "confirmDoctorAppointment",
        "security": [
          {
            "pru_api_auth": [
              "write:doctors"
            ]
          }
        ]
      }
    },
    "/doctor/appointment/response": {
      "post": {
        "tags": [
          "Doctor"
        ],
        "summary": "Doctor Appointment Confirmation",
        "description": "",
        "operationId": "updateDoctorAppointment"
      }
    },
    "/workflow/{id}": {
      "get": {
        "tags": [
          "Workflow"
        ],
        "summary": "Find workflow status by Id",
        "description": "Return workflow by Id",
        "operationId": "getWorkflowById",
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/user": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Create User",
        "description": "Create User",
        "operationId": "createUser"
      }
    },
    "/user/login": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Login User",
        "description": "Login User",
        "operationId": "login"
      }
    },
    "/user/{id}": {
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update User",
        "description": "Update User",
        "operationId": "updateUser",
        "security": [
          {
            "pru_api_auth": [
              "write:users"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Delete User",
        "description": "Delete User",
        "operationId": "deleteUser",
        "security": [
          {
            "pru_api_auth": [
              "delete:users"
            ]
          }
        ]
      }
    },
    "/user/changePassword": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Change Password",
        "description": "Change Password",
        "operationId": "changePassword",
        "security": [
          {
            "pru_api_auth": [
              "write:users"
            ]
          }
        ]
      }
    },
    "/user/resetPassword": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Reset Password",
        "description": "Reset Password",
        "operationId": "resetPassword"
      }
    },
    "/user/otp": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Submit Otp",
        "description": "Submit Otp",
        "operationId": "submitOtp"
      }
    },
    "/user/logout": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Logout User",
        "description": "Logout User",
        "operationId": "logout",
        "security": [
          {
            "pru_api_auth": [
              "write:users"
            ]
          }
        ]
      }
    },
    "/user/refreshToken": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Refresh Access Token",
        "description": "",
        "operationId": "refreshToken"
      }
    },
    "/entity": {
      "post": {
        "tags": [
          "Data"
        ],
        "summary": "Create Entity in data lake",
        "description": "Create Entity in data lake",
        "operationId": "createEntity",
        "security": [
          {
            "pru_api_auth": [
              "write:entity",
              "read:entity"
            ]
          }
        ]
      }
    },
    "/entity/{id}": {
      "put": {
        "tags": [
          "Data"
        ],
        "summary": "Update Entity in data lake",
        "description": "Update Entity in data lake",
        "operationId": "updateEntity",
        "security": [
          {
            "pru_api_auth": [
              "write:entity",
              "read:entity"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Data"
        ],
        "summary": "Get Entity from data lake",
        "description": "Get Entity from data lake",
        "operationId": "readEntity",
        "security": [
          {
            "pru_api_auth": [
              "write:entity",
              "read:entity"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Data"
        ],
        "summary": "Delete Entity in data lake",
        "description": "Delete Entity in data lake",
        "operationId": "deleteEntity",
        "security": [
          {
            "pru_api_auth": [
              "write:entity",
              "read:entity"
            ]
          }
        ]
      }
    },
    "/entity/search": {
      "post": {
        "tags": [
          "Data"
        ],
        "summary": "Search Entities in data lake",
        "description": "Search Entities in data lake",
        "operationId": "queryEntity",
        "security": [
          {
            "pru_api_auth": [
              "write:entity",
              "read:entity"
            ]
          }
        ]
      }
    },
    "/entity/{id}/exist": {
      "get": {
        "tags": [
          "Data"
        ],
        "summary": "Check if entity exist in data lake",
        "description": "Check if entity exist in data lake",
        "operationId": "existEntity",
        "security": [
          {
            "pru_api_auth": [
              "write:entity",
              "read:entity"
            ]
          }
        ]
      }
    },
    "/message": {
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Send email,sms message to destination",
        "description": "Send email,sms message to destination",
        "operationId": "sendMessage",
        "security": [
          {
            "pru_api_auth": [
              "write:message"
            ]
          }
        ]
      }
    },
    "/fund/amc": {
      "get": {
        "tags": [
          "Fund"
        ],
        "summary": "Find all Asset Management companies (Fund Houses)",
        "description": "Return all Asset management companies (Fund Houses)",
        "operationId": "getAllAmc",
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/fund/search": {
      "post": {
        "tags": [
          "Fund"
        ],
        "summary": "Find fund by query criteria",
        "description": "",
        "operationId": "findFundsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "write:fund",
              "read:fund"
            ]
          }
        ]
      }
    },
    "/fund/{fundCode}/detail": {
      "get": {
        "tags": [
          "Fund"
        ],
        "summary": "Get details of the fund",
        "description": "Get details of the fund",
        "operationId": "getFundDetail",
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/fund/{fundCode}/performance": {
      "get": {
        "tags": [
          "Fund"
        ],
        "summary": "Get Fund Performance",
        "description": "Get Fund Performance",
        "operationId": "getFundPerformance",
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/campaign": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Create new campaign",
        "description": "",
        "operationId": "createCampaign",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/{id}/pause": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Pause campaign",
        "description": "",
        "operationId": "pauseCampaign",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/{id}/start": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Start campaign",
        "description": "",
        "operationId": "startCampaign",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Find campaigns by query criteria",
        "description": "",
        "operationId": "findCampaignsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/{id}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Find campaign by Id",
        "description": "Returns a single campaign",
        "operationId": "getCampaignById",
        "security": [
          {
            "api_key": []
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "summary": "Update an existing campaign",
        "description": "",
        "operationId": "updateCampaign",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Campaign"
        ],
        "summary": "Delete a campaign",
        "description": "Delete a campaign",
        "operationId": "deleteCampaign",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/{id}/segment/{segId}/statistics": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Find campaign statistics by Id",
        "description": "Returns campaign statistics",
        "operationId": "getCampaignStatsById",
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/campaign/{id}/segment/{segId}/distList": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Get campaign DistributionList",
        "description": "Returns campaign DistributionList",
        "operationId": "getCampaignDistributionList",
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/campaign/{id}/segments": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Get campaign segments",
        "description": "Returns campaign segments",
        "operationId": "getCampaignSegmentsById",
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/campaign/segment": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Create new segment",
        "description": "",
        "operationId": "createCampaignSegment",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/segment/search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Find campaign Segments by query criteria",
        "description": "",
        "operationId": "findCampaignSegmentsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/segment/{id}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Find campaign segment by Id",
        "description": "Returns a single campaign segment",
        "operationId": "getCampaignSegmentById",
        "security": [
          {
            "api_key": []
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "summary": "Update an existing campaign segment",
        "description": "",
        "operationId": "updateCampaignSegment",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Campaign"
        ],
        "summary": "Delete a campaign segment",
        "description": "Delete a campaign segment",
        "operationId": "deleteCampaignSegment",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/distList": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Create new distribution list",
        "description": "",
        "operationId": "createDistributionList",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/distList/search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Find Distribution Lists by query criteria",
        "description": "",
        "operationId": "findDistListsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/campaign/distList/{id}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Find campaign segment by Id",
        "description": "Returns a single distribution list",
        "operationId": "getDistributionListById",
        "security": [
          {
            "api_key": []
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "summary": "Update an existing distribution list",
        "description": "",
        "operationId": "updateDistributionList",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Campaign"
        ],
        "summary": "Delete a distribution list",
        "description": "Delete distribution list",
        "operationId": "deleteDistributionList",
        "security": [
          {
            "pru_api_auth": [
              "write:campaign",
              "read:campaign"
            ]
          }
        ]
      }
    },
    "/hospital/search": {
      "post": {
        "tags": [
          "Hospital"
        ],
        "summary": "Find hospital by Criteria",
        "description": "",
        "operationId": "findHospitalsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "search:hospitals"
            ]
          }
        ]
      }
    },
    "/hospital/{id}": {
      "post": {
        "tags": [
          "Hospital"
        ],
        "summary": "Get Hospital by Id",
        "description": "",
        "operationId": "getHospitalId",
        "security": [
          {
            "pru_api_auth": [
              "read:hospitals"
            ]
          }
        ]
      }
    },
    "/hospital/{id}/doctors": {
      "post": {
        "tags": [
          "Hospital"
        ],
        "summary": "Find All Doctors by Hospital Id",
        "description": "",
        "operationId": "findDoctorsByHospitalId",
        "security": [
          {
            "pru_api_auth": [
              "search:hospitals"
            ]
          }
        ]
      }
    },
    "/hospital/{id}/rooms": {
      "get": {
        "tags": [
          "Hospital"
        ],
        "summary": "Get All Rooms by Hospital Id",
        "description": "",
        "operationId": "getRoomsByHospitalId",
        "security": [
          {
            "pru_api_auth": [
              "search:hospitals"
            ]
          }
        ]
      }
    },
    "/geolocation/feature": {
      "post": {
        "tags": [
          "Geo location"
        ],
        "summary": "Get feature by Criteria",
        "description": "",
        "operationId": "getGeoFeatureByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "search:geolocations"
            ]
          }
        ]
      }
    },
    "/resource/{id}": {
      "get": {
        "tags": [
          "Resource"
        ],
        "summary": "Find resource by Id",
        "description": "Returns a single resource",
        "operationId": "getResourceById"
      }
    },
    "/resources": {
      "get": {
        "tags": [
          "Resource"
        ],
        "summary": "get All resources by Ids",
        "description": "Returns a list of resources",
        "operationId": "getResourcesByIds"
      }
    },
    "/partner/id/generate": {
      "post": {
        "tags": [
          "Partner"
        ],
        "summary": "Generate Id for external entity",
        "description": "",
        "operationId": "generateExternalId",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/chat/{id}/session": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Get chat session",
        "description": "Returns chat session",
        "operationId": "getChatSession",
        "security": [
          {
            "pru_api_auth": [
              "write:customers"
            ]
          }
        ]
      }
    },
    "/notification": {
      "post": {
        "tags": [
          "Notification"
        ],
        "summary": "Notify customer",
        "description": "",
        "operationId": "notification",
        "security": [
          {
            "pru_api_auth": [
              "write:doctor_external"
            ]
          }
        ]
      }
    },
    "/group": {
      "post": {
        "tags": [
          "Group"
        ],
        "summary": "Create group",
        "description": "",
        "operationId": "createGroup",
        "security": [
          {
            "pru_api_auth": [
              "write:groups"
            ]
          }
        ]
      }
    },
    "/group/{id}": {
      "get": {
        "tags": [
          "Group"
        ],
        "summary": "Get group by Id",
        "description": "Returns a single group",
        "operationId": "getGroupById",
        "security": [
          {
            "pru_api_auth": [
              "read:groups"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Group"
        ],
        "summary": "Update an existing group",
        "description": "",
        "operationId": "updateGroup",
        "security": [
          {
            "pru_api_auth": [
              "write:groups"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Group"
        ],
        "summary": "Delete a group",
        "description": "",
        "operationId": "deleteGroup",
        "security": [
          {
            "pru_api_auth": [
              "delete:groups"
            ]
          }
        ]
      }
    },
    "/groups": {
      "get": {
        "tags": [
          "Group"
        ],
        "summary": "Get all groups",
        "description": "Returns all group",
        "operationId": "getAllGroups",
        "security": [
          {
            "pru_api_auth": [
              "read:groups"
            ]
          }
        ]
      }
    },
    "/group/search": {
      "post": {
        "tags": [
          "Group"
        ],
        "summary": "Find group by query criteria",
        "description": "",
        "operationId": "findGroupByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "search:groups"
            ]
          }
        ]
      }
    },
    "/group/{id}/members": {
      "get": {
        "tags": [
          "Group"
        ],
        "summary": "Get all group members",
        "description": "",
        "operationId": "getGroupMembers",
        "security": [
          {
            "pru_api_auth": [
              "read:groups"
            ]
          }
        ]
      }
    },
    "/event/query": {
      "post": {
        "tags": [
          "Event"
        ],
        "summary": "Query Events by query criteria",
        "description": "",
        "operationId": "findEventsByCriteria",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    },
    "/wearables": {
      "get": {
        "tags": [
          "Wearables"
        ],
        "summary": "Get All Supported Wearables",
        "description": "",
        "operationId": "getAllWearables",
        "security": [
          {
            "pru_api_auth": [
              "read:customers"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "pru_api_auth": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "http://api.prudential.com/oauth/dialog",
            "tokenUrl": "http://api.prudential.com/oauth/token",
            "scopes": {
              "write:customers": "modify customers",
              "read:customers": "read customers",
              "search:customers": "search customers",
              "delete:customers": "delete customers",
              "write:products": "modify products",
              "read:products": "read products",
              "search:products": "search products",
              "delete:products": "delete products",
              "write:underwritings": "modify underwritings",
              "read:underwritings": "read underwritings",
              "write:agents": "modify agents",
              "read:agents": "read agents",
              "search:agents": "search agents",
              "delete:agents": "delete agents",
              "write:claims": "modify claims",
              "read:claims": "read claims",
              "search:claims": "search claims",
              "delete:claims": "delete claims",
              "write:policy": "modify policy",
              "read:policy": "read policy",
              "search:policy": "search policy",
              "delete:policy": "delete policy",
              "write:proposal": "modify proposal",
              "read:proposal": "read proposal",
              "search:proposal": "search proposal",
              "delete:proposal": "delete proposal",
              "write:quote": "modify quote",
              "read:quote": "read quote",
              "search:quote": "search quote",
              "delete:quote": "delete quote",
              "write:documents": "modify documents",
              "read:documents": "read documents",
              "write:billing": "modify billing",
              "read:billing": "read billing",
              "write:payment": "modify payment",
              "read:payment": "read payment",
              "search:doctors": "search doctors",
              "write:doctors": "write doctors",
              "read:doctors": "read doctors",
              "write:users": "write users",
              "read:users": "read users",
              "write:entity": "write entity",
              "read:entity": "read entity",
              "read:message": "read message",
              "write:message": "write message",
              "read:fund": "read fund",
              "write:fund": "write fund",
              "read:campaign": "read campaign",
              "write:campaign": "write campaign",
              "search:hospitals": "search hospitals",
              "read:hospitals": "read hospitals",
              "write:hospitals": "write hospitals",
              "search:geolocations": "search geolocations",
              "read:geolocations": "read geolocations",
              "write:geolocations": "write geolocations",
              "search:groups": "search groups",
              "read:groups": "read groups",
              "write:groups": "write groups",
              "delete:groups": "delete groups"
            }
          }
        }
      },
      "api_key": {
        "type": "apiKey",
        "name": "api_key",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "pru_api_auth": []
    },
    {
      "apiKey": []
    }
  ]
}